title: "Marat211 Blog"
description: "A simple personal blog powered by Jekyll."
url: "https://marat211.github.io"
baseurl: ""

minima:
  nav_pages:
    - abou.md
    - portfolio.md

theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
permalink: /:categories/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
